sys:
  batch: 10000
  partition: 20
  maxPollWait: 5000
  cleanInterval: 3600000
  dataKeepHours: 24
  syncTriggerInterval: 300000
  retryInterval: 20000
  endpointPort: 8081


monitor:
  - matches:
      heartbeatLostOver: 5
      syncBlockedOver: 100
      syncErrorOver: 10
      syncPendingOver: 1000
    action: webhook
    params:
      url: http://x.x.x.x:xxxx/

db:
  - name: db1
    type: greenplum
    driver: org.postgresql.Driver
    url: jdbc:postgresql://x.x.x.x:xxxx/db
    user: user
    password: password
    sysSchema: dbsync
    createIndex: true
    maxPoolSize: 5
  - name: db2
    type: mysql
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://x.x.x.x:xxxx/db
    user: xxxx
    password: xxxx
    sysSchema: dbsync
    createIndex: false

sync:
  - sourceDb: db2
    targetDb: db1
    sourceSchema: test
    sourceTable: test01
    sourceKeys: f1,f2
    targetSchema: public