sys:
  batch: 10000
  partition: 20
  maxPollWait: 5000
  cleanInterval: 60000
  syncTriggerInterval: 60000
  retryInterval: 60000
  dataKeepHours: 24

monitor:
  - name: email
    matches:
      heartbeatLostOver: 5
      syncBlockedOver: 100
      syncErrorOver: 10
      syncPendingOver: 1000
    action: email
    params:
      host: xxxx
      port: 1234
      user: xxx
      password: xxx
      from: xxx
      to: xxx
      subject: xxx
  - name: xxx
    matches:
      heartbeatLostOver: 5
      syncBlockedOver: 100
      syncErrorOver: 10
      syncPendingOver: 1000
    action: webhook
    params:
      url: http://x.x.x.x:xxxx/path
  - name: restart
    matches:
      heartbeatLostOver: 10
    action: restart

db:
  - name: db1
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/test
    user: admin
    password: password
    sysSchema: dbsync
    createIndex: true
  - name: db2
    type: mysql
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    user: admin
    password: password
    sysSchema: dbsync
    createIndex: true

sync:
  - sourceDb: db2
    targetDb: db1
    sourceSchema: test
    sourceTable: test01
    sourceKeys: f1,f2